### ISSUE TITLE
ULF

### ISSUE THREAD

**Issue by rocktavious** [Hermesiss/unity-package-manager-ci#1]
Hey @Hermesiss Is this your personal unity license file?  https://github.com/Hermesiss/unity-package-manager-ci/blob/master/ci/Unity_v2018.x.ulf

You might want to remove that from this repo because if it is your personal license then anyone could steal it and download all the asset store packages you've paid for.

**Comment by Hermesiss** [comment]
Thanks, @rocktavious ! Used its encrypted version for another CI and missed while making this repo
